// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJGhmBvXp6MWOjYlDvdoAmNqIwqLBhlFo',
    appId: '1:666334585654:web:0b921d747543c79af18997',
    messagingSenderId: '666334585654',
    projectId: 'fca-to-do-list',
    authDomain: 'fca-to-do-list.firebaseapp.com',
    storageBucket: 'fca-to-do-list.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2CzJ52pLq-Pazjbx84ki23vXERM78lQk',
    appId: '1:666334585654:android:81c3edb5c4b73216f18997',
    messagingSenderId: '666334585654',
    projectId: 'fca-to-do-list',
    storageBucket: 'fca-to-do-list.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJvlwb74Jv9tXIyD_b7fJpG3diHdUZ5_w',
    appId: '1:666334585654:ios:5a1a4ce878a6156ff18997',
    messagingSenderId: '666334585654',
    projectId: 'fca-to-do-list',
    storageBucket: 'fca-to-do-list.appspot.com',
    iosBundleId: 'com.example.flutterLearningGoRouter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJvlwb74Jv9tXIyD_b7fJpG3diHdUZ5_w',
    appId: '1:666334585654:ios:5a1a4ce878a6156ff18997',
    messagingSenderId: '666334585654',
    projectId: 'fca-to-do-list',
    storageBucket: 'fca-to-do-list.appspot.com',
    iosBundleId: 'com.example.flutterLearningGoRouter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJGhmBvXp6MWOjYlDvdoAmNqIwqLBhlFo',
    appId: '1:666334585654:web:2856972aa4870c88f18997',
    messagingSenderId: '666334585654',
    projectId: 'fca-to-do-list',
    authDomain: 'fca-to-do-list.firebaseapp.com',
    storageBucket: 'fca-to-do-list.appspot.com',
  );
}
